### ISSUE TITLE
Financial damages caused by received errors $$$$

### ISSUE THREAD

**Issue by karloti** [google-gemini/generative-ai-android#164] opened 2024-05-31 07:33 UTC
### I used this library [(generative-ai-android](https://github.com/google-gemini/generative-ai-android)) v0.6.0  on Gemini 1.5 Pro and it caused me financial damage!

I was getting errors instead of replies from Gemini and ended up getting **charged**. 
`Something went wrong while trying to deserialize a response from the server. for: (Ask Gemini)`
`Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected 'null' literal when non-nullable string was expected (Ask Gemini)
`

200 prompts cycled through, which I had to repeat every few seconds until I got a result other than an error. 

**So I was charged **millions of tokens <128k**.** 

Since Gemini 1.5 Pro is still in **preview**, and the Android library itself is **not stable**, who should **bear the brunt**, when I have not received other than errors.

How at such an early stage, something that is still a prototype can cause financial damage to my company?

We've wasted enough time testing, and now money.

I stopped the Gemini API because I don't plan on using the library until this issue is resolved.

I'm sure I won't be the only one, but I might be the first to suffer.

These mistakes are paid with real money.

Please tell me in this situation, which I have provided you with the most detailed information by email, who will take responsibility for the recovery of damages?

### Actual vs expected behavior:

At first, I was very happy that there is already such a library, although the problem of storing the API key is not solved. Such a library is vital for the next generation of Android applications that need to quickly and conveniently implement generative AI solutions. I used the library for testing, and instead of contributing to its improvement, I managed to waste money and a lot of time. My expectations were not met. I expect that such decisions should be given some credit so that one can realistically assess how they are charged. Until May 30th, I didn't have any token counting accuracy, and now suddenly, in addition to them, the bills came in the billing. I think such incidents should be taken into account because there will be many people like me.

**Comment by davidmotson** [comment] 2024-06-03 19:01
marking as a duplicate of 160

**Closed by davidmotson** 2024-06-03 19:01 UTC
Labels: type:bug, component:android sdk, status:triaged
