### ISSUE TITLE
PLEASE FIX THIS! "Something went wrong while trying to deserialize a response from the server."

### ISSUE THREAD

**Issue by karloti** [google-gemini/generative-ai-android#162] opened 2024-05-30 15:05 UTC
### Description of the bug:
Currently reporting requests to Gemini which I'm being **billed** for even though I'm getting errors from the library, no fault of mine. 

Please tell me what to do? This library has a serialization error. I repeatedly repeat the request until I get a response that is not an error and thus incur insanely large amounts of money.
Is there a way to not charge these errors?

![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/d8bbb1bc-94db-4f90-beab-3641218ee895)

[dump.txt](https://github.com/google-gemini/generative-ai-android/files/15502126/dump.txt)

### Actual vs expected behavior:
I expect not to be charged for a library error!

### Any other information you'd like to share?

When I do a prompt, even though I get an error, it gets charged. Since errors are not handled well, I repeat the prompt until it returns a non-error result. This is done every 15 seconds. After all, for about 20 replies, I can have 2000 inquiries charged. I don't know how to avoid this problem. I use functional calling and prompts for in Bulgarian.

**Comment by davidmotson** [comment] 2024-05-30 17:43
Closing as duplicate of #160

**Closed by davidmotson** 2024-05-30 17:43 UTC
